In [1]:
from tkinter import *
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("dataset.csv")

In [3]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [4]:
df.shape

(303, 14)

In [5]:
df.columns
del df['age']
del df['sex']
df.columns

Index(['cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang',
       'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [6]:
#cp
cp=[*range(4)] 
cp
chol=[*range(120,350, 10)]

In [7]:
#trestbps
trestbps=[*range(100, 200, 10)] 
trestbps

[100, 110, 120, 130, 140, 150, 160, 170, 180, 190]

In [8]:
#fbs
fbs=[0,1]
#restecg
restecg=[0,1]
thalac=[*range(100,200, 10)]
exang=[0,1]
oldpeak=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.2,1.4,1.6,1.8,1.9,2.0,3.1,3.2,3.4,3.5,3.7,3.9,4.1,4.3,4.5]
oldpeak
slope=[0,1,2]
ca=[0,1,2,3,4]
thal=[1,2,3]

In [9]:
# entries
OPTIONS1 = sorted(cp)
OPTIONS2 = sorted(trestbps)
OPTIONS3 = sorted(chol)
OPTIONS4 = sorted(fbs)
OPTIONS5 = sorted(restecg)
OPTIONS6 = sorted(thalac)
OPTIONS7 = sorted(exang)
OPTIONS8 = sorted(oldpeak)
OPTIONS9 = sorted(slope)
OPTIONS10 = sorted(ca)
OPTIONS11= sorted(thal)

In [10]:
X= df.drop(labels='target', axis=1)
y=df[['target']]


np.ravel(y)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [11]:
X_test= df.drop(labels='target', axis=1)
y_test =[df.loc[:,'target']]
np.ravel(y_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [12]:
df.head()

,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,3,145,233,1,0,150,0,2.3,0,0,1,1
1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,1,130,204,0,0,172,0,1.4,2,0,2,1
3,1,120,236,0,1,178,0,0.8,2,0,2,1
4,0,120,354,0,1,163,1,0.6,2,0,2,1

In [13]:


def DecisionTree():

   import joblib
   terms = [[cp1.get(),trestbps1.get(),chol1.get(),fbs1.get(),restecg1.get(),thalac1.get(),exang1.get(),
   oldpeak1.get(),slope1.get(),ca1.get(),thal1.get()]]
   #load the logistic regression pickle file
   classifier = joblib.load('final_models/dt_final.pkl')
   #checking and predicting
   #checkprediction = inputScript.main(url)
   prediction = classifier.predict(terms)
   print(prediction)
   predicted=prediction[0]
   t1.delete("1.0", END)
   t1.insert(END, predicted)

In [14]:
def randomforest():
    import joblib
    terms = [[cp1.get(),trestbps1.get(),chol1.get(),fbs1.get(),restecg1.get(),thalac1.get(),exang1.get(),
    oldpeak1.get(),slope1.get(),ca1.get(),thal1.get()]]
    #load the logistic regression pickle file
    classifier = joblib.load('final_models/rf_final.pkl')
   
    prediction = classifier.predict(terms)
    print(prediction)
    predicted=prediction[0]
    t2.delete("1.0", END)
    t2.insert(END, predicted)

In [15]:

def lr():
    import joblib
    terms = [[cp1.get(),trestbps1.get(),chol1.get(),fbs1.get(),restecg1.get(),thalac1.get(),exang1.get(),
    oldpeak1.get(),slope1.get(),ca1.get(),thal1.get()]]
    #load the logistic regression pickle file
    classifier = joblib.load('final_models/logisticR_final.pkl')
    #checking and predicting
    #checkprediction = inputScript.main(url)
    prediction = classifier.predict(terms)
    print(prediction)
    predicted=prediction[0]
    t3.delete("1.0", END)
    t3.insert(END, predicted)

In [16]:

def SVC():
    import joblib
    
    terms = [[cp1.get(),trestbps1.get(),chol1.get(),fbs1.get(),restecg1.get(),thalac1.get(),exang1.get(),
    oldpeak1.get(),slope1.get(),ca1.get(),thal1.get()]]
    
    #importing the dataset
    dataset = pd.read_csv("dataset.csv")
    dataset = dataset.drop('age',1) #removing unwanted column
    dataset = dataset.drop('sex',1) #removing unwanted column
    x = dataset.iloc[ : , :-1].values
    y = dataset.iloc[:, -1:].values

    #load the logistic SVC pickle file
    classifier = joblib.load('final_models/svm_final.pkl')
    #checking and predicting
    #checkprediction = inputScript.main(url)
    prediction = classifier.predict(terms)
    print(prediction)
    predicted=prediction[0]

    t4.delete("1.0", END)
    t4.insert(END, predicted)

In [17]:
root = Tk()
root.title("Heart Disease Prediction")
#root.configure(background='black')
canvas = Canvas(root,width=1880,height=1253)
canvas.pack()
photo = PhotoImage(file ='heart1.png')
canvas.create_image(0,0,image=photo,anchor=NW)


# entry variables

cp1 = IntVar()
trestbps1 = IntVar()
chol1 = IntVar()
fbs1 = IntVar()
restecg1 = IntVar()
thalac1 = IntVar()
exang1 = IntVar()
oldpeak1 = IntVar()
slope1 = IntVar()
ca1 = IntVar()
thal1 = IntVar()

# Heading
w2 = Label(canvas, justify=LEFT, text="Heart Disease Prediction using Machine Learning", fg="white", bg="red")
w2.config(font=("Elephant", 20))
w2.grid(row=1, column=0, columnspan=2, padx=100)
w2 = Label(canvas, justify=LEFT, text="Hospital", fg="green")
w2.config(font=("Times Roman", 15))
w2.grid(row=2, column=0, columnspan=2, padx=100)

# labels
lb1 = Label(canvas, height=1, width=30, text="Chest Pain Type",fg="yellow", bg="black")
lb1.grid(row=5, column=0, pady=15, sticky=W)
mn1 = OptionMenu(canvas, cp1,*OPTIONS1)
mn1.grid(row=5, column=0)

lb2 = Label(canvas, height=1, width=30, text="TrestBps",fg="yellow", bg="black")
lb2.grid(row=5, column=1, pady=15, sticky=W)
mn2 = OptionMenu(canvas, trestbps1,*OPTIONS2)
mn2.grid(row=5, column=1)

lb3 = Label(canvas, height=1, width=30, text="Cholestrol",fg="yellow", bg="black")
lb3.grid(row=6, column=0, pady=15, sticky=W)
mn3 = OptionMenu(canvas, chol1,*OPTIONS3)
mn3.grid(row=6, column=0)

lb4 = Label(canvas, height=1, width=30, text="FBS",fg="yellow", bg="black")
lb4.grid(row=6, column=1, pady=15, sticky=W)
mn4 = OptionMenu(canvas, fbs1,*OPTIONS4)
mn4.grid(row=6, column=1)

lb5 = Label(canvas, height=1, width=30, text="Rest ECG",fg="yellow", bg="black")
lb5.grid(row=7, column=0, pady=15, sticky=W)
mn5 = OptionMenu(canvas, restecg1,*OPTIONS5)
mn5.grid(row=7, column=0)

lb6 = Label(canvas, height=1, width=30, text="Thalac",fg="yellow", bg="black")
lb6.grid(row=7, column=1, pady=15, sticky=W)
mn6 = OptionMenu(canvas, thalac1,*OPTIONS6)
mn6.grid(row=7, column=1)

lb7 = Label(canvas, height=1, width=30,text="Exang",fg="yellow", bg="black")
lb7.grid(row=8, column=0, pady=15, sticky=W)
mn7 = OptionMenu(canvas, exang1,*OPTIONS7)
mn7.grid(row=8, column=0)

lb8 = Label(canvas, height=1, width=30, text="Old Peak",fg="yellow", bg="black")
lb8.grid(row=8, column=1, pady=15, sticky=W)
mn8 = OptionMenu(canvas, oldpeak1,*OPTIONS8)
mn8.grid(row=8, column=1)

lb9 = Label(canvas, height=1, width=30, text="Slope",fg="yellow", bg="black")
lb9.grid(row=9, column=0, pady=15, sticky=W)
mn9 = OptionMenu(canvas, slope1,*OPTIONS9)
mn9.grid(row=9, column=0)

lb10 = Label(canvas, height=1, width=30, text="CA Type",fg="yellow", bg="black")
lb10.grid(row=9, column=1, pady=15, sticky=W)
mn10 = OptionMenu(canvas, ca1,*OPTIONS10)
mn10.grid(row=9, column=1)

lb11 = Label(canvas, height=1, width=30, text="thal",fg="yellow", bg="black")
lb11.grid(row=10, column=0, pady=15, sticky=W)
mn11 = OptionMenu(canvas, thal1,*OPTIONS11)
mn11.grid(row=10, column=0)

In [18]:


destreeLb = Label(canvas, text="DecisionTree", fg="white", bg="red")
destreeLb.grid(row=14, column=0, pady=10,sticky=W)

ranfLb = Label(canvas, text="RandomForest", fg="white", bg="red")
ranfLb.grid(row=15, column=0, pady=10, sticky=W)

lrLb = Label(canvas, text="LogisticRegression", fg="white", bg="red")
lrLb.grid(row=16, column=0, pady=10, sticky=W)



svLb = Label(canvas, text="SVC", fg="white", bg="red")
svLb.grid(row=17, column=0, pady=10, sticky=W)

In [19]:

dst = Button(canvas, text="DecisionTree Algorithm", command=DecisionTree,bg="cyan",fg="green")
dst.grid(row=14, column=1,padx=10)

rnf = Button(canvas, text="Randomforest Algorithm", command=randomforest,bg="cyan",fg="green")
rnf.grid(row=15, column=1,padx=10)

lr = Button(canvas, text="LogisticRegression Algorithm", command=lr,bg="cyan",fg="green")
lr.grid(row=16, column=1,padx=10)



sv = Button(canvas, text="SVC Algorithm", command=SVC,bg="cyan",fg="green")
sv.grid(row=17, column=1,padx=10)

In [20]:

#textfileds
t1 = Text(canvas, height=1, width=40,bg="orange",fg="black")
t1.grid(row=14, column=0, padx=10)

t2 = Text(canvas, height=1, width=40,bg="orange",fg="black")
t2.grid(row=15, column=0 , padx=10)

t3 = Text(canvas, height=1, width=40,bg="orange",fg="black")
t3.grid(row=16, column=0 , padx=10)


t4 = Text(canvas, height=1, width=40,bg="orange",fg="black")
t4.grid(row=17, column=0 , padx=10)

root.mainloop()

Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "<ipython-input-13-fead842a7c08>", line 3, in DecisionTree
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib' from 'sklearn.externals' (D:\Anaconda3\lib\site-packages\sklearn\externals\__init__.py)
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "<ipython-input-14-34ae3e9a7396>", line 2, in randomforest
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib' from 'sklearn.externals' (D:\Anaconda3\lib\site-packages\sklearn\externals\__init__.py)
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "<ipython-input-15-4fe3f7da1982>", line 2, in lr
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib' from 'sklearn.externals' (D:\Anaconda3\lib\site-packages\sklearn\externals\__init__.py)
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "<ipython-input-16-c76f15975487>", line 2, in SVC
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib' from 'sklearn.externals' (D:\Anaconda3\lib\site-packages\sklearn\externals\__init__.py)